[build]
    command = "npm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "10.15"

[context.production.environment]
    NODE_ENV = "production"

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
